CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Idle after 10sec
CONFIG_ZMK_IDLE_TIMEOUT=10000

# Lower power usage at the expense of responsiveness
# fastest rate of communication with the host device. 1.25ms increments. dflt 24.
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=40
# bt max connection interval. 1.25ms inc. dflt 40
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=60
# preferred latency in Connection Intervals.
# => how many kbd events can be skipped. dflt 0
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0